package com.vlascitchii.presentation_common.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF00288E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF003AC4)
val onPrimaryContainerLight = Color(0xFFA8B8FF)
val secondaryLight = Color(0xFF4F5B92)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB4C1FF)
val onSecondaryContainerLight = Color(0xFF414D83)
val tertiaryLight = Color(0xFF5B0074)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF7A1797)
val onTertiaryContainerLight = Color(0xFFED9EFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1A1B23)
val surfaceLight = Color(0xFFFBF8FF)
val onSurfaceLight = Color(0xFF1A1B23)
val surfaceVariantLight = Color(0xFFE0E1F3)
val onSurfaceVariantLight = Color(0xFF444654)
val outlineLight = Color(0x99747686)
val outlineVariantLight = Color(0xFFC4C5D7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3038)
val inverseOnSurfaceLight = Color(0xFFF1F0FB)
val inversePrimaryLight = Color(0xFFB8C4FF)
val surfaceDimLight = Color(0xFFDAD9E4)
val surfaceBrightLight = Color(0xFFFBF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F2FE)
val surfaceContainerLight = Color(0xFFEEEDF8)
val surfaceContainerHighLight = Color(0xFFE8E7F3)
val surfaceContainerHighestLight = Color(0xFFE2E1ED)


val primaryDark = Color(0xFFB8C4FF)
val onPrimaryDark = Color(0xFF002585)
val primaryContainerDark = Color(0xFF003AC4)
val onPrimaryContainerDark = Color(0xFFA8B8FF)
val secondaryDark = Color(0xFFB8C4FF)
val onSecondaryDark = Color(0xFF1F2C61)
val secondaryContainerDark = Color(0xFF374379)
val onSecondaryContainerDark = Color(0xFFA6B2EF)
val tertiaryDark = Color(0xFFF1AFFF)
val onTertiaryDark = Color(0xFF54006C)
val tertiaryContainerDark = Color(0xFF7A1797)
val onTertiaryContainerDark = Color(0xFFED9EFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF11131B)
val onBackgroundDark = Color(0xFFE2E1ED)
val surfaceDark = Color(0xFF11131B)
val onSurfaceDark = Color(0xFFE2E1ED)
val surfaceVariantDark = Color(0xFF444654)
val onSurfaceVariantDark = Color(0xFFC4C5D7)
val outlineDark = Color(0x998E90A0)
val outlineVariantDark = Color(0xFF444654)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E1ED)
val inverseOnSurfaceDark = Color(0xFF2F3038)
val inversePrimaryDark = Color(0xFF2951D8)
val surfaceDimDark = Color(0xFF11131B)
val surfaceBrightDark = Color(0xFF373941)
val surfaceContainerLowestDark = Color(0xFF0C0E15)
val surfaceContainerLowDark = Color(0xFF1A1B23)
val surfaceContainerDark = Color(0xFF1E1F27)
val surfaceContainerHighDark = Color(0xFF282932)
val surfaceContainerHighestDark = Color(0xFF33343D)

val toolbarLogoFixed = Color(0xFF00288E)